name: Build and Push Docker Image

on:
  push:
    branches:
      - main    # Trigger action when code is pushed to the 'main' branch
      - dev     # Trigger action when code is pushed to the 'dev' branch
  pull_request:
    branches:
      - main    # Trigger action when a pull request is created for 'main'
      - dev     # Trigger action when a pull request is created for 'dev'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/vista-monte-mar-be:${{ github.event_name == 'push' && github.ref_name || github.head_ref }}
